Config = {}

Config.OpeningTime = 5000

Config.Locations = {
    ["seller"] = { -- Kayu
        type = 4,
        model = "u_m_y_pogo_01",
        hash = 0xDC59940D,
        location = vector4(-136.68, 229.74, 93.95, 358.07)
    },
}

Config.CardColors = {
    ["basic"] = {
        color1 = "#fff",
        color2 = "#fff",
        color3 = "#fff",
        color4 = "#fff",
        border_size = 6, -- in px
        border_color = "#999",
        -- Effect
        shining = false,
        sparkles = false,
    },
    ["rare"] = {
        color1 = "#af13ce",
        color2 = "#87a593",
        color3 = "#ffbe33",
        color4 = "#ffcf33",
        border_size = 6, -- in px
        border_color = "#999",
        -- Effect
        shining = false,
        sparkles = true,
    },
    ["legendary"] = {
        color1 = "#e09a3d",
        color2 = "#41ece4",
        color3 = "#ff9f9f",
        color4 = "#ff7676",
        border_size = 6, -- in px
        border_color = "#999",
        -- Effect
        shining = true,
        sparkles = true,
    },
}
Config.Cards = {
 -- Base
    {
        color = "basic",
        rank = "basic",
        label = "Abruh",
        images = "img/abruh.png",
        description = "Bestia, Altezza: 90, Peso: 19",
        term = "Psichico",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Boolbiesore",
        images = "img/boolbiesore.png",
        description = "Bestia, Altezza: 70, Peso: 7",
        term = "Foglielama",
        health = 70,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Charman",
        images = "img/charman.png",
        description = "Bestia, Altezza: 60, Peso: 8",
        term = "Braciere",
        health = 70,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Charmmelon",
        images = "img/charmmelon.png",
        description = "Bestia, Altezza: 110, Peso: 19",
        term = "Rogodenti",
        health = 90,
        attack = 40,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Coughing",
        images = "img/coughing.png",
        description = "Bestia, Altezza: 60, Peso: 1",
        term = "Smog",
        health = 70,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Coughing X2",
        images = "img/coughingx2.png",
        description = "Bestia, Altezza: 120, Peso: 10",
        term = "Fango",
        health = 100,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Cutebone",
        images = "img/cutebone.png",
        description = "Bestia, Altezza: 40, Peso: 6",
        term = "Fangoberla",
        health = 60,
        attack = 10,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Ditoe",
        images = "img/ditoe.png",
        description = "Bestia, Altezza: 30, Peso: 4",
        term = "Azione",
        health = 60,
        attack = 10,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Dragonnodle",
        images = "img/dragonnodle.png",
        description = "Bestia, Altezza: 40, Peso: 10",
        term = "Dragopulsar",
        health = 100,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Dug ",
        images = "img/dug.png",
        description = "Bestia, Altezza: 20, Peso: 1",
        term = "Terremoto",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Dug il Terzo",
        images = "img/dugilterzo.png",
        description = "Bestia, Altezza: 70, Peso: 33",
        term = "Maledizione",
        health = 100,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Eve",
        images = "img/eve.png",
        description = "Bestia, Altezza: 30, Peso: 18",
        term = "Sdoppiatore",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Fidget",
        images = "img/fidget.png",
        description = "Bestia, Altezza: 30, Peso: 2",
        term = "Spennata",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Flameo",
        images = "img/flameo.png",
        description = "Bestia, Altezza: 90, Peso: 25",
        term = "Fuocobomba",
        health = 90,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Geobro",
        images = "img/geobro.png",
        description = "Bestia, Altezza: 40, Peso: 20",
        term = "Pietrataglio",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Golfbat",
        images = "img/golfbat.png",
        description = "Bestia, Altezza: 160, Peso: 55",
        term = "Velenocroce",
        health = 90,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Green Onion",
        images = "img/greenonion.png",
        description = "Bestia, Altezza: 80, Peso: 15",
        term = "Beccata",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Hitmanchaa",
        images = "img/hitmanchaa.png",
        description = "Bestia, Altezza: 140, Peso: 50",
        term = "Centripugno",
        health = 90,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Hitmanlee",
        images = "img/hitmanlee.png",
        description = "Bestia, Altezza: 150, Peso: 50",
        term = "Calcinvolo",
        health = 90,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Iiviisore",
        images = "img/iiviisore.png",
        description = "Bestia, Altezza: 100, Peso: 13",
        term = "Energipalla",
        health = 90,
        attack = 40,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Jincks",
        images = "img/jincks.png",
        description = "Bestia, Altezza: 140, Peso: 41",
        term = "Psicoshock",
        health = 80,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Jinglebell",
        images = "img/jinglebell.png",
        description = "Bestia, Altezza: 50, Peso: 5",
        term = "Botta",
        health = 60,
        attack = 10,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Kadabruh",
        images = "img/kadabruh.png",
        description = "Bestia, Altezza: 130, Peso: 57",
        term = "Divinazione",
        health = 80,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Magitarp",
        images = "img/magitarp.png",
        description = "Bestia, Altezza: 90, Peso: 10",
        term = "Azione",
        health = 30,
        attack = 10,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Martini",
        images = "img/martini.png",
        description = "Bestia, Altezza: 180, Peso: 3",
        term = "Tornado",
        health = 70,
        attack = 30,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Paris",
        images = "img/paris.png",
        description = "Bestia, Altezza: 30, Peso: 5",
        term = "Furto",
        health = 50,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Polygon",
        images = "img/polygon.png",
        description = "Bestia, Altezza: 80, Peso: 37",
        term = "Facciata",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Ramen",
        images = "img/ramen.png",
        description = "Bestia, Altezza: 100, Peso: 35",
        term = "Gigassorbimento",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Seal",
        images = "img/seal.png",
        description = "Bestia, Altezza: 110, Peso: 88",
        term = "Surf",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Sir Meow",
        images = "img/sirmeow.png",
        description = "Bestia, Altezza: 40, Peso: 4",
        term = "Azione",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Snailboi",
        images = "img/snailboi.png",
        description = "Bestia, Altezza: 40, Peso: 7",
        term = "Cascata",
        health = 80,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Squishy",
        images = "img/squishy.png",
        description = "Bestia, Altezza: 50, Peso: 8",
        term = "Idrondata",
        health = 60,
        attack = 20,
        icon = "",
        quality = 100,
    },
    {
        color = "basic",
        rank = "basic",
        label = "Warsquishy",
        images = "img/warsquishy.png",
        description = "Bestia, Altezza: 100, Peso: 23",
        term = "Idropulsar",
        health = 90,
        attack = 30,
        icon = "",
        quality = 100,
    },
  --Raro
    {
        color = "rare",
        rank = "rare",
        label = "Alakablam",
        images = "img/alakablam.png",
        description = "Bestia, Altezza: 150, Peso: 48",
        term = "Cozzata Zen",
        health = 120,
        attack = 60,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Blastoff",
        images = "img/blastoff.png",
        description = "Bestia, Altezza: 160, Peso: 85",
        term = "Zampillo",
        health = 120,
        attack = 70,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Charlard",
        images = "img/charlard.png",
        description = "Bestia, Altezza: 170, Peso: 90",
        term = "Rabbia Bruciante",
        health = 140,
        attack = 75,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Dragonmight",
        images = "img/dragonmight.png",
        description = "Bestia, Altezza: 220, Peso: 210",
        term = "Iper Raggio",
        health = 140,
        attack = 100,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Ganger",
        images = "img/ganger.png",
        description = "Bestia, Altezza: 150, Peso: 41",
        term = "Palla Ombra",
        health = 130,
        attack = 70,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Gerald",
        images = "img/gerald.png",
        description = "Bestia, Altezza: 650, Peso: 235",
        term = "Idropompa",
        health = 130,
        attack = 100,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Kanghascam",
        images = "img/kanghascam.png",
        description = "Bestia, Altezza: 220, Peso: 80",
        term = "Gigaimpatto",
        health = 130,
        attack = 100,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Marrowhack",
        images = "img/marrowhack.png",
        description = "Bestia, Altezza: 100, Peso: 45",
        term = "Fuococarica",
        health = 100,
        attack = 60,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Ricechu",
        images = "img/ricechu.png",
        description = "Bestia, Altezza: 80, Peso: 30",
        term = "Fulmine",
        health = 100,
        attack = 60,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Snoremax",
        images = "img/snoremax.png",
        description = "Bestia, Altezza: 210, Peso: 460",
        term = "Gigaimpatto",
        health = 120,
        attack = 60,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Veenuhsore",
        images = "img/veenuhsore.png",
        description = "Bestia, Altezza: 200, Peso: 155",
        term = "Fangobomba",
        health = 120,
        attack = 60,
        icon = "",
        quality = 100,
    },
    {
        color = "rare",
        rank = "rare",
        label = "Wingletough",
        images = "img/wingletough.png",
        description = "Bestia, Altezza: 100, Peso: 12",
        term = "Incantavoce",
        health = 100,
        attack = 40,
        icon = "",
        quality = 100,
    },
--Leggendario
    {
        color = "legendary",
        rank = "legendary",
        label = "Ew",
        images = "img/ew.png",
        description = "Bestia, Altezza: 40, Peso: 4",
        term = "Psichico",
        health = 160,
        attack = 150,
        icon = "",
        quality = 100,
    },
    {
        color = "legendary",
        rank = "legendary",
        label = "EwTwo",
        images = "img/ewtwo.png",
        description = "Bestia, Altezza: 200, Peso: 122",
        term = "Iper Raggio",
        health = 190,
        attack = 170,
        icon = "",
        quality = 100,
    },
    {
        color = "legendary",
        rank = "legendary",
        label = "Molten",
        images = "img/molten.png",
        description = "Bestia, Altezza: 200, Peso: 60",
        term = "Aeroassalto",
        health = 180,
        attack = 120,
        icon = "",
        quality = 100,
    },
    {
        color = "legendary",
        rank = "legendary",
        label = "Shiny Charlard",
        images = "img/shinycharlard.png",
        description = "Bestia, Altezza: 280, Peso: 110",
        term = "Lanciafiamme",
        health = 180,
        attack = 120,
        icon = "",
        quality = 100,
    },
    {
        color = "legendary",
        rank = "legendary",
        label = "Zapdude",
        images = "img/zapdude.png",
        description = "Bestia, Altezza: 160, Peso: 53",
        term = "Elettrocannone",
        health = 190,
        attack = 120,
        icon = "",
        quality = 100,
    },


}